title: Welcome to codedrj
author: codedrj
email: codedrj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code built by codedrj. 
# social links
twitter_username: codedrj
github_username:  codedrj

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
